# Generated by Django 4.2.6 on 2023-10-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField()),
                ('latitude', models.IntegerField()),
                ('longtitude', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='for_test.store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='workers',
            field=models.ManyToManyField(to='for_test.worker'),
        ),
    ]
