# Generated by Django 4.2.6 on 2023-10-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0002_alter_visit_date_of_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='longtitude',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
