# Generated by Django 4.2.6 on 2023-10-12 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0004_visit_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='latitude',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='longtitude',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='store',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='for_test.store'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='worker',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='for_test.worker'),
        ),
    ]
